# Version de docker compose
version: "3"
# Servicios
services:
    # Contenedor para la base de datos mongodb
    mongodb:
        image: mongo:3.0.2
        command: mongod --port 27018
        ports:
            - '27018:27018'
    # Contenedor para el portfolio
    portfolio:
         # Nombre del contenedor
        container_name: portfolio
        # Construccion del contenedor
        build:
            # Indicamos que el dockerfile se encuentra en el directorio actual
            context: .
            # Argumentos para la construcción
            args:
                PORT: ${PORT}
                DB_URI: ${DB_URI}
        # Variables de entorno
        environment:
            - PORT=${PORT}
            - DB_URI=${DB_URI}
        # Puertos
        ports:
            - "${PORT}:${PORT}"
        # portfolio depende de mongodb
        depends_on:
            - mongodb
