# Version de docker compose
version: "3"
# Servicios
services:
    # Contenedor para la base de datos mongodb
    mongodb:
        image: mongo:3.0.2
        command: mongod --port 27018
        ports:
            - '27018:27018'
    # Contenedor para el microservicio portfolio
    portfolio:
         # Nombre del contenedor
        container_name: portfolio
        # Construccion del contenedor
        build:
            # Indicamos que el dockerfile se encuentra en el directorio actual
            context: .
            # Argumentos para la construcción
            args:
                PORT_PORTFOLIO: ${PORT_PORTFOLIO}
                DB_URI: ${DB_URI}
        # Variables de entorno
        environment:
            - PORT_PORTFOLIO=${PORT_PORTFOLIO}
            - DB_URI=${DB_URI}
        # Puertos
        ports:
            - "${PORT_PORTFOLIO}:${PORT_PORTFOLIO}"
        # portfolio depende de mongodb
        depends_on:
            - mongodb
    # Contenedor para el microservicio mercado
    mercado:
         # Nombre del contenedor
        container_name: mercado
        # Construccion del contenedor
        build:
            # Indicamos que el dockerfile se encuentra en el directorio Mercado
            context: ./src/Mercado
            # Argumentos para la construcción
            args:
                PORT_MARKET: ${PORT_MARKET}
        # Variables de entorno
        environment:
            - PORT_MARKET=${PORT_MARKET}
        # Puertos
        ports:
            - "${PORT_MARKET}:${PORT_MARKET}"
