name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.6, 3.7, 3.8]

    services:
        mongodb:
            image: mongo:3.4.23
            ports:
            - 27017:27017
    env:
        DB_NAME_PORTFOLIO: ${{ secrets.DB_NAME_PORTFOLIO }}
        DB_URI: ${{ secrets.DB_URI }}
        PORT: ${{ secrets.PORT }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install invoke
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pip install -r requirements.txt
        invoke test
    - name: Test with pytest-cov
      run: |
        pip install -r requirements.txt
        invoke coverage
